import { genReactQueryDefault, genReactQueryDefaultAxiosUnwrapResponseData, genReactQueryDefaultFetch, genReactQueryDefaultFetchUnwrapResponseData, genReactQueryModular, genReactQueryModularAxiosUnwrapResponseData, genReactQueryModularFetch, genReactQueryModularFetchUnwrapResponseData, genVueQueryDefault, genVueQueryDefaultAxiosUnwrapResponseData, genVueQueryDefaultFetch, genVueQueryDefaultFetchUnwrapResponseData, genVueQueryModular, genVueQueryModularAxiosUnwrapResponseData, genVueQueryModularFetch, genVueQueryModularFetchUnwrapResponseData } from './utils'

genReactQueryDefault()
genReactQueryDefaultFetch()
genReactQueryDefaultFetchUnwrapResponseData()
genReactQueryDefaultAxiosUnwrapResponseData()

genReactQueryModular()
genReactQueryModularFetch()
genReactQueryModularFetchUnwrapResponseData()
genReactQueryModularAxiosUnwrapResponseData()

genVueQueryDefault()
genVueQueryDefaultFetch()
genVueQueryDefaultFetchUnwrapResponseData()
genVueQueryDefaultAxiosUnwrapResponseData()

genVueQueryModular()
genVueQueryModularFetch()
genVueQueryModularFetchUnwrapResponseData()
genVueQueryModularAxiosUnwrapResponseData()
